version: '3'

services:
  demo-lidarhd-classe:
    container_name: demo-lidarhd-classe
    build:
      context: "."  
      dockerfile: Dockerfile
      args:    
        - http_proxy
        - https_proxy
    environment:
      - HTTP_PROXY=${HTTP_PROXY}
      - HTTPS_PROXY=${HTTPS_PROXY}
      - ACCESS_KEY=${ACCESS_KEY}
      - SECRET_KEY=${SECRET_KEY}
      - BUCKET=${BUCKET}
      - ENDPOINT_URL=${ENDPOINT}
      - REGION_NAME=${REGION}
      - HOST_SERVEUR=${HOST_SERVEUR}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - PGDATABASE=${PGDATABASE}
      - PGPORT=${PGPORT}
      - PGHOST=${PGHOST}
    ports:
      - '5000:5000'
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./app:/app
  
  db:
    image: kartoza/postgis:15-3.3
    volumes:
      - postgis-data:/var/lib/postgresql
      - dbbackups:/backups
    environment:
      # If you need to create multiple database you can add coma separated databases eg gis,data
      - POSTGRES_DB=gis
      - POSTGRES_USER=docker
      - POSTGRES_PASS=docker
      - ALLOW_IP_RANGE=0.0.0.0/0
      # Add extensions you need to be enabled by default in the DB. Default are the five specified below
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting
      - RUN_AS_ROOT=true
    ports:
      - "5432"
    restart: on-failure
    healthcheck:
      test: "PGPASSWORD=docker pg_isready -h 127.0.0.1 -U docker -d gis"
      interval: 10s
      timeout: 10s
      retries: 4

  adminer:
    image: adminer
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8080:8080
  
volumes:
  postgis-data:
  dbbackups:
